set nocompatible

set number
set ruler
syntax on

set tabstop=2
set expandtab

set wrap
set linebreak

set hlsearch
set incsearch
set ignorecase
set smartcase
nnoremap <Space> :set hlsearch!<CR>

set scrolloff=3

set undodir=~/.vim/undo//
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//

set showcmd

set history=100

set t_Co=256

